### ISSUE TITLE
Klasse LightController

### ISSUE THREAD

**Issue by WasIsDaLos** [HoferAnton/NetzwerkeI#7]
Die Klasse Light Controller muss noch als Thread ausgeschrieben werden, der gegebenenfalls die Lichter im 5 Sekundentakt aktualisiert. Ich habe mir da als erste Idee gedacht, dass in einem bool array gespeichert werden soll, ob sich seit dem letzten Intervall etwas geeändert hat. Das sollte vermeiden, dass die Lampen alle 5 Sekunden einen unnötigen PUT Request erhalten. Außerdem muss noch das Blinken der orangenen Leuchte implementiert werden. Das sollte nicht alzu schwer sein.

**Comment by WasIsDaLos** [comment]
Der LightController ist jetzt als Thread lauffähig. Ich habe nur noch keine elegante Idee wie ich das Licht orange blinken lassen soll. Mann soll es anscheinend per Thread machen, aber ich frage mich wie ich das ohne weitere Klasse machen soll. Fazit der LightController kann verwendet werden, aber orange blinkt noch nicht.

**Comment by HoferAnton** [comment]
Ja Thread heißt eigene Klasse. Eventuell einen Thread bauen der alle halbe sekunde die Lampe aus und wieder an macht.  Sobald dann der Thread interrupted wird einfach den Thread sterben lassen. Das müsste sich eigentlich nicht so schwer gestalten.
Kannst du mal nachschauen welches Encoding dein Eclips verwendet. wenn ich deine Dateien öffne bekomm ich encoding fehler.

**Comment by HoferAnton** [comment]
Schön wäre es wenn der Thread dann die Werte der einzelnen Taxis aus dem Controller nimmt. 
:smile:

**Comment by WasIsDaLos** [comment]
Der Controller läuft ja bereits als Thread und steuert die Lampen, aber dann werde ich halt noch eine zusätzliche Klasse für das Blinken machen müssen. Man muss dem Controller nur sagen welche Lampe wie geschaltet werden soll und mit dem nächsten Update( alle 5 Sekunden) setzt er das um.

**Comment by WasIsDaLos** [comment]
Also am encoding kanns kaum liegen, weil ich das nicht geändert habe und du den Upload davor ja auch anschauen konntest oder? Auf github wird es zumindest richtig angezeigt.

**Comment by HoferAnton** [comment]
Ok habs gelöst die datei ConnectionEvaluator ist in ISO-8859-1 nicht utf-8

**Comment by WasIsDaLos** [comment]
Okay komisch. Naja die Lichter blinken jetzt auf jeden Fall rot auf Anfrage.

**Comment by HoferAnton** [comment]
Deswegen halt die Frage als was eclipse diese Datei handhabt

**Comment by HoferAnton** [comment]
Wie genau hängt sich dein Code jetzt an den TaxiServer?

**Comment by HoferAnton** [comment]
Also wie ist momentan die Testkonfig für die Lampen?

**Comment by WasIsDaLos** [comment]
Also es ist jetzt so gedacht, dass sich der TaxiServer ein LightController Objekt erstellt und es per run laufen lässt. Sobald eine Änderung an den Lampen gemacht werden soll muss die Methode changeLightAtNextCycle(oder so ähnlich) genutzt werden, um dem Controller mitzuteilen welche Lampe wie geändert werden soll. Mann übergibt einfach nur die Lampe und den Enumtyp für die Farbe(vielleicht muss man den noch public machen).

**Comment by HoferAnton** [comment]
Ja die Frage ist aber in unserem Fall woher weis der Controller welche Farbe er mitteilen soll.

**Comment by HoferAnton** [comment]
Die Taxis im controller haben halt alle nötigen Informationen , diese werden dann von dem Controller irgendwie verarbeitet damit dann die Lampen angesteuert werden können.

**Comment by HoferAnton** [comment]
Dementsprechend ist aktuell die Frage wie wir das Ansprechen deiner Klassen handlen wollen und daran sitz ich grad.

**Comment by WasIsDaLos** [comment]
Kann das nicht der TaxiServer übernehmen, da hier alle Informationen gespeichert werden?

**Comment by HoferAnton** [comment]
Bedingt ja bedingt nein. Ich muss halt den Server soweit umbauen dass er die Informationen so an deine Klassen senden kann.

**Comment by HoferAnton** [comment]
Und daran arbeite ich gerade.

**Comment by WasIsDaLos** [comment]
Danke das du die ganzen Einzelteile zusammenfügst. Ich kann gerne auch noch etwas übernehmen, wenn dir noch was einfällt. Würde ich dann morgen Nachmittag/Abend machen. Heute bin ich noch mit SE und DBS verplant.

**Comment by HoferAnton** [comment]
Nur zur info wegen dem Encoding hab ich die ä/ü/ö usw. aus deinen dateien geschmissen, connte sonst nicht compilieren.

**Comment by HoferAnton** [comment]
Ne frage woher kommen so sachen wie appcode appid usw. die du für die API brauchst?

**Comment by WasIsDaLos** [comment]
Das sind Daten, die von here.com gestellt wurden. Die sind verbunden mit meinem Account und verifizieren den Zugriff, bzw. weisen ihn mir zu, da man ja "nur" 100.000 Zugriffe pro Monat hat.

**Comment by HoferAnton** [comment]
ok danke

**Comment by HoferAnton** [comment]
ok danke ich rechne ab dort dann sowieso nur noch mit Duration und nicht mehr mit Zahlen aber dort ists halt wichtig # TaxiServer updateTaxi 
:smile:

**Comment by HoferAnton** [comment]
Der Light controller startet alle lampen mit Active hab ich geändert zunächst sollten eigentlich alle inactive sein, oder?

**Comment by HoferAnton** [comment]
OMG ich war vielleicht grad am verzweifeln....
Problem irgendwie wille er mir nur den neuen Befehl, dass ein Taxi active oder inactive sein kann nicht senden... rumgedoktert schon so am verzweifeln und dann hab ich festgestellt das ich den Befehl einfach unter ner anderen Order gesendet hab... 😞  Naja aber jetzt funktionierts...
Wie hast du das eigentlich gelöst das der bei Orange blinkt?

**Comment by HoferAnton** [comment]
Folgendes entweder ich mach was falsch oder deine Methode hat nen Fehler:
folgendes:
`
CURRENT ORDER: 
{"order":"InitiateTrip","name":"taxi1","position":"Kloster Moosen 26","destination":"Lothstraße 64a","time":1500000}
Exception in thread "Thread-3" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.eclipsesource.json.JsonArray.get(JsonArray.java:416)
	at taxiapplication.ConnectionEvaluator.getGeoCoordinatesFromAdress(ConnectionEvaluator.java:106)
	at taxiapplication.ConnectionEvaluator.getRouteTime(ConnectionEvaluator.java:55)
	at taxiapplication.TaxiServer.updateTaxi(TaxiServer.java:110)
	at taxiapplication.TaxiConnection.applyOrder(TaxiConnection.java:106)
	at taxiapplication.TaxiConnection.commitToServer(TaxiConnection.java:62)
	at taxiapplication.ConnectionQueueHandler.run(ConnectionQueueHandler.java:65)`

**Comment by HoferAnton** [comment]
Also ich lad jetzt mal was hoch Bitte merk dir deine Changes lokal. Ich muss drüberpushen weil ich nicht weis wo ich dann in der Datei was geändert hab oder nicht.

**Comment by HoferAnton** [comment]
Ok nach dem ReadLight Push hat mich github rausgeschmissen...

**Comment by HoferAnton** [comment]
Ich fürchte Das Rot licht wirst du noch mal in den Light Controller integrieren müssen..

**Comment by HoferAnton** [comment]
nach Aktuellem Stand hört die Lampe nicht mehr auf zu blinken und der Fahrer wird nach abschluss der von Ihm gegebenen Fahrt nicht automatisch frei.
