### ISSUE TITLE
Aufgabe 7

### ISSUE THREAD

**Issue by HoferAnton** [HoferAnton/NetzwerkeI#9]
Erste Aufgabe wird das Alternating Bit Protocol sein.

**Comment by WasIsDaLos** [comment]
Da hätt ich wohl erst mal auf das Issue schauen sollen. Hab den Empfänger mit Platzhaltern erstellt. Werde das aber noch ändern.

**Comment by WasIsDaLos** [comment]
Aber hatten wir nicht eigentlich eine andere Reihenfolge ausgemacht, oder trifft das nur für das erste Packet zu?
Laut dem Bild das du mit geschickt hast war es:
1) Prüfsumme
2)alternating bit
3)fin bit

**Comment by HoferAnton** [comment]
soweit ich das sehe war eigentlich eine Reihenfolge nicht definiert...
Daher habe ich eigenlich mal nen Vorschlag dafür gemacht.
Wenn du die Reihenfolge anders haben willst kann ich sie gerne ändern.

**Comment by WasIsDaLos** [comment]
Danke das du die beiden Teile integriert hast. Tut mir Leid das ich erst jetzt zurückschreibe, aber bis ins neue Jahr wollte ich frei haben und dann bin ich leider krank geworden.

**Comment by WasIsDaLos** [comment]
Ich bau die Datenrate dann noch ein.

**Comment by WasIsDaLos** [comment]
Hab gerade gesehen, das du das auch schon gemacht hast. Danke auch dafür.
